### ISSUE TITLE
Yet another defvao VBO problem

### ISSUE THREAD

**Issue by mfiano** [lispgames/glkit#11]
I have the following spec

``` lisp
(defvao :mesh ()
  (:interleave (:divisor 1)
   (offsets :float 3)
   (colors :float 3))
  (:interleave (:divisor 0)
   (position :float 3)
   (normal :float 3)
   (uv :float 3)))
```

In my shader I have the following attributes:

```
layout (location = 0) in vec3 offsets;
layout (location = 1) in vec3 colors;
layout (location = 2) in vec3 position;
layout (location = 3) in vec3 normal;
layout (location = 4) in vec3 uv;
```

This works perfect.

However, it will NOT work if the instance array (divisor 1 layout) is defined second instead of first, and the shader locations changed to match. It does not matter if the layout is :separate or :interleave - it just seems that given 2 layouts, divisor 1 and divisor 0, the divisor 1 MUST come first.

The result is the shader sees the attributes as if they were empty arrays. Changing vertex colors to any attribute of any instance always results in black.

Luckily, this is a problem that can be easily worked around, ensuring divisor 1 vbo's are always defined first, but it took me a couple hours to realize that and will save lots of headaches in the future if this can be looked into. I can provide more information if needed.

**Comment by rpav** [comment]
Hrm I had a few ideas for how this might be broken, but none of them seem to be the case.  In particular, given your definition above, if I swap the `:divisor` between groups, it gets parsed/stored into the second group correctly.

Once that's the case, it's pretty much passed through directly and only depends on `INDEX` being correct... if that were broken, attributes should be considerably more broken.

I would recommend:
1. Check that they're parsing correctly for you, i.e. evaluate the `defvao`, inspect the resulting `vao-declaration`, look at the `GROUPS` slot and at a particular group.  `DIVISOR` is a slot of a `vertex-attribute-group`.  You should be able to change the divisor and see it in the right group.
2. `src/vao/vao.lisp` L60 is where the divisor actually gets set.  Put a print here or something and watch the divisor and index and see if they correlate correctly.

**Comment by rpav** [comment]
(To clarify, this was an issue enabling attributes when multiple groups were present.)

**Comment by mfiano** [comment]
Fixed.
