### ISSUE TITLE
static-vectors fails to compile

### ISSUE THREAD

**Issue by mfiano** [lispgames/glkit#2]
static-vectors still fails to compile on windows even with commit 1e870f. The problem occurs when quickloading glkit master - it attempts to pull in static-vectors as a dependency and spits out an error saying sbcl on windows is unable to redirect output when executing a gcc command.

**Comment by rpav** [comment]
Oh, are you not using SBCL?

**Comment by mfiano** [comment]
This happens on SBCL for Windows only

**Comment by rpav** [comment]
Wait, I'm not sure how this could be.  Does your SBCL-on-windows not have `:sbcl` and `:windows` in `*features*`?

**Comment by mfiano** [comment]
Confirmed fixed with :win32

**Comment by rpav** [comment]
Oh right. :)
